### ISSUE TITLE
Tooltip issues on IE11

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-tooltip#15]
Noticed 2 issues while working with charts with the tooltip.
Seems isolated to IE11 but will need more testing.

1. On hover over data points in polar, the tooltip arrow is turned into a detached diamond - separated from the tooltip border frames.
2. When the window is resized to mobile, the tooltip arrow is misaligned and not pointing in the correct direction.

Screenshots of both issues attached.

![tooltip_on_resize](https://cloud.githubusercontent.com/assets/10835611/20731433/43ba740a-b63f-11e6-9ef0-fe1c671e9e6a.png)

![tooltip_on_polar_ie](https://cloud.githubusercontent.com/assets/10835611/20731564/c8bded76-b63f-11e6-9234-0ca702e36a07.png)

**Tooltip version:** 0.9.4

-------------------------------------------------------------
A more recent screenshot on IE11, with tooltip version: 0.10.18

![tooltip_arrow_off_ie](https://user-images.githubusercontent.com/10835611/26946714-17c50c06-4c45-11e7-9393-80e0eb9bc041.png)

**Comment by benoitjchevalier** [comment]
We now managed to reproduce on other browsers on vis 1.0.0. Need to fix

**Comment by ppeyro** [comment]
Adding additional issues being tracked on IE11:

![tooltip-issue1](https://user-images.githubusercontent.com/10835611/29383833-bb773906-8286-11e7-8269-20fd83141241.PNG)


![tooltip-issue2](https://user-images.githubusercontent.com/10835611/29383835-c0478f3a-8286-11e7-80ba-962a40869860.PNG)
