### ISSUE TITLE
tooltip dosen't break sentence when required

### ISSUE THREAD

**Issue by mailmrmanoj** [predixdesignsystem/px-tooltip#36]
I'm trying bind customize message that I fetch from controller and pass to px-tooltip

```
 <px-tooltip orientation="bottom" opened="true" [attr.tooltip-message]="tooltipMessage">
  </px-tooltip>

  this.tooltipMessage="November 2016 <br> This is my customized tooltip message";
```

I would like to bring the message "This is my customized tooltip message " under "November 2016".
I tried using  break , new line " \n" but dosen't seem to work.

**Comment by evanjd** [comment]
You can provide your own tooltip HTML by just nesting it within the `px-tooltip` element. For example:

```html
<style>
  .tooltip-example span {
    display: block;
  }
</style>

<px-tooltip for="btn1" delay="50" orientation="auto">
  <div class="tooltip-example">
    <span>This is one line.</span>
    <span>This is another!</span>
  </div>
</px-tooltip>
<button id="btn1">Hover over me</button>
```

Gets you:
<img width="257" alt="screen shot 2018-12-12 at 9 54 35 pm" src="https://user-images.githubusercontent.com/4055224/49865241-8a8eed80-fe58-11e8-9684-3c2bb5084a91.png">

Here's a glitch if you want to see in action: https://glitch.com/edit/#!/px-tooltip-multiline-example

**Comment by mailmrmanoj** [comment]
Thanks @evanjd .When I try this its breaking the lines, but the text is appearing outside the tooptip.Please let men know which css I need to modify to make the text apper inside the tooltip box?

**Comment by evanjd** [comment]
There’s CSS in the examples I posted (my last comment and in the glitch link). Did they not work for you? And if not, can you please replicate your issue in a glitch/jsfiddle?

**Comment by mailmrmanoj** [comment]
Thanks for the update @evanjd .Had issue with my application due to which css were overriding tooltip's css. Got fixed it!!
